#!/bin/bash
## Execute "curl -sSL https://raw.githubusercontent.com/avides/docker-scripts/master/docker-swarm-reschedule-sh | sh"

docker service ls | while IFS= read -r line ; do

	name=$(echo $line | awk '{print $2;}' )
	replicas=$(echo $line | awk '{print $4}');

	if [ "$name" == "NAME" ]; then continue; fi

	replicasRunning=$(echo $replicas | awk -F '/' '{print $1}');
	replicasExpected=$(echo $replicas | awk -F '/' '{print $2}');

	if [ "$replicasRunning" -ne "$replicasExpected" ]; then

		echo "$name - $replicasRunning/$replicasExpected";
		docker service update --force $name --with-registry-auth;

	fi

done
